In [ ]:
# def find_best(X, y, c):
#     smallest_error = np.Inf
#     best_index = -1
#     error = 0.0
#     ls = []
#     for coeff in c:
#         for xi,yi in zip(X,y):
#             error = error + ((xi @ coeff) - yi)**2
#         ls.append(error)
#     print(ls)
#     best_index = ls.index(min(ls))
#     print(best_index)
        
             # edit here: calculate the sum of squared error with coefficient set coeff and
                 # keep track of the one yielding the smallest squared error
#     print("the best set is set %d" % best_index)
# max_index = fishers.index(max(fishers))

#find_best(X, y, c)

In [8]:
import numpy as np

# data
X = np.array([[66, 5, 15, 2, 500], 
              [21, 3, 50, 1, 100], 
              [120, 15, 5, 2, 1200]])
y = np.array([250000, 60000, 525000])

# alternative sets of coefficient values
c = np.array([[3000, 200 , -50, 5000, 100], 
              [2000, -250, -100, 150, 250], 
              [3000, -100, -150, 0, 150]])   

def find_best(X, y, c):
    smallest_error = np.Inf
    best_index = -1
    new_y = []
    for coeff in c:
        new_y.append(X @ coeff)
    error = []
    for i in range(len(new_y)):
        k = 0.0
        for m,n in zip(y,new_y[i]):
            k = k + (m-n)**2
        error.append(k)
    print(error)
    best_index = error.index(min(error))    
        
    print(new_y)
    print(best_index)
#         pass     # edit here: calculate the sum of squared error with coefficient set coeff and
#                  # keep track of the one yielding the smallest squared error
#     print("the best set is set %d" % best_index)
find_best(X,y,c)

[1367335000.0, 144765000.0, 676665000.0]
[array([258250,  76100, 492750]), array([254550,  61400, 536050]), array([270250,  70200, 537750])]
1


In [5]:
import numpy as np

X = np.array([[66, 5, 15, 2, 500], 
              [21, 3, 50, 1, 100], 
              [120, 15, 5, 2, 1200]])
y = np.array([250000, 60000, 525000])
c = np.array([3000, 200 , -50, 5000, 100])    # coefficient values
 

sse = 0.0
y_new = X @ c
for m,n in zip(y,y_new):
    sse = sse + (m-n)**2
    print(m)
    print(n)

print(sse)
# for xi, yi in zip(X, y):

#         # add your code here: calculate the predicted price,
#         # subtract it from the actual price yi, 
#         # square the difference using (yi - prediction)**2, 
#         # and add up all the differences in variable sse
# see = sse = sse + ((xi @ c) - yi)**2

# print(sse)



250000
258250
60000
76100
525000
492750
1367335000.0


In [ ]:
1367335000.0
144765000


In [25]:
import numpy as np
a = np.array(
        [
            [25, 2, 50, 1, 500], 
            [39, 3, 10, 1, 1000], 
            [13, 2, 13, 1, 1000], 
            [82, 5, 20, 2, 120], 
            [130, 6, 10, 2, 600],
        ]
)

b = np.array([
    [115,6,10,1,550]
]
)
c = np.concatenate((a,b),axis=0)
print(c)

[[  25    2   50    1  500]
 [  39    3   10    1 1000]
 [  13    2   13    1 1000]
 [  82    5   20    2  120]
 [ 130    6   10    2  600]
 [ 115    6   10    1  550]]


In [23]:
c=np.arange(1,5).reshape(2,2)
d = np.concatenate((c,c), axis=0)
print(d)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [47]:
import numpy as np
from io import StringIO

input_string = '''
25 2 50 1 500 127900
39 3 10 1 1000 222100
13 2 13 1 1000 143750
82 5 20 2 120 268000
130 6 10 2 600 460700
115 6 10 1 550 407000
'''

np.set_printoptions(precision=1)    # this just changes the output settings for easier reading
f = StringIO(input_string)
a = np.genfromtxt(f,dtype = None)
#print(a)
n = a.shape[1]
#print(n)

x = a[:,0:n-1]
#print(x)
#价格
y = a[:,n-1]
#print(y)

x1 = x[0:5]
y1 = y[0:5]
c = np.linalg.lstsq(x1, y1 ,rcond=None)[0]
print(c)

# def fit_model(input_file):
#     # Please write your code inside this function

#     # read the data in and fit it. the values below are placeholder values
#     c = np.asarray([])  # coefficients of the linear regression
#     x = np.asarray([])  # input data to the linear regression

#     print(c)
#     print(x @ c)

# # simulate reading a file
# input_file = StringIO(input_string)
# fit_model(input_file)

[3000.  200.  -50. 5000.  100.]


In [49]:
import numpy as np
from io import StringIO

input_string = '''
25 2 50 1 500 127900
39 3 10 1 1000 222100
13 2 13 1 1000 143750
82 5 20 2 120 268000
130 6 10 2 600 460700
115 6 10 1 550 407000
'''

np.set_printoptions(precision=1)    # this just changes the output settings for easier reading
 
def fit_model(input_file):
    # Please write your code inside this function
    a = np.genfromtxt(input_file,dtype = None)
    n = a.shape[1]
    x = a[:,0:n-1]
    y = a[:,n-1]
    x1 = x[0:5]
    y1 = y[0:5]
    print(x1)
    print(y1)
    c = np.linalg.lstsq(x1, y1 ,rcond=None)[0]
    # read the data in and fit it. the values below are placeholder values
    # c = np.asarray([])  # coefficients of the linear regression
    # x = np.asarray([])  # input data to the linear regression

    print(c)
    print(x @ c)

# simulate reading a file
input_file = StringIO(input_string)
fit_model(input_file)

[[  25    2   50    1  500]
 [  39    3   10    1 1000]
 [  13    2   13    1 1000]
 [  82    5   20    2  120]
 [ 130    6   10    2  600]]
[127900 222100 143750 268000 460700]
[3000.  200.  -50. 5000.  100.]
[127900. 222100. 143750. 268000. 460700. 405700.]


In [51]:
import math
print(math.sqrt(153))

12.36931687685298


In [52]:
import math
a = [14, 3, 0.8]
b = [2, 6, 0.8]

import numpy as np

def dist(a, b):
    sum = 0
    for ai, bi in zip(a, b):
        sum = sum + (ai - bi)**2
    return np.sqrt(sum)

print(dist(a,b))

12.36931687685298


In [54]:
import numpy as np

x_train = np.random.rand(10, 3)   # generate 10 random vectors of dimension 3
x_test = np.random.rand(3)        # generate one more random vector of the same dimension

print("training:",x_train)
print("test:",x_test)

training: [[0.8 0.  1. ]
 [0.6 0.  0.8]
 [0.2 0.6 0.6]
 [0.  0.8 0.5]
 [0.2 0.8 0.9]
 [0.4 0.5 0.3]
 [0.8 0.4 0.7]
 [0.2 0.4 0.6]
 [0.3 0.2 0.2]
 [0.4 0.8 0.1]]
test: [0.8 0.1 0.4]


In [ ]:
import math
import numpy as np

x_train = np.array([[25, 2, 50, 1, 500], 
                  [39, 3, 10, 1, 1000],    
                  [82, 5, 20, 2, 120], 
                  [130, 6, 10, 2, 600]])
y_train = [127900, 222100,  268000, 460700]

x_test = np.array([[115, 6, 10, 1, 560], [13, 2, 13, 1, 1000]])


def dist(a, b):
    sum = 0
    for ai, bi in zip(a, b):
        sum = sum + (ai - bi)**2
    return np.sqrt(sum)

n_train = len(x_train) # number of data points in the training set

for test_item in x_test:
    d = np.empty(n_train) # d will hold the distances between this test data point and all the training data points
    for i, train_item in enumerate(x_train):
        d[i] = dist(test_item, train_item)
    nearest_index = np.argmin(d) # the nearest neighbour will be in y_train[nearest]
    print(y_train[nearest_index])

In [ ]:
# list方法
# array方法

In [ ]:
import numpy as np

x_train = np.random.rand(10, 3)   # generate 10 random vectors of dimension 3
x_test = np.random.rand(3)        # generate one more random vector of the same dimension

def dist(a, b):
    sum = 0
    for ai, bi in zip(a, b):
        sum = sum + (ai - bi)**2
    return np.sqrt(sum)
    
def nearest(x_train, x_test):
    nearest = -1
    min_distance = np.Inf
    distance = []
    # add a loop here that goes through all the vectors in x_train and finds the one that
    # is nearest to x_test. return the index (between 0, ..., len(x_train)-1) of the nearest
    # neighbor
    for i in range(len(x_train)):
        distance.append(dist(x_train[i],x_test))
    nearest = distance.index(min(distance))
    print(nearest)

nearest(x_train, x_test)

In [63]:
import numpy as np
from sklearn.datasets import make_blobs
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


# create random data with two classes
X, y = make_blobs(n_samples=16, n_features=2, centers=2, center_box=(-2, 2))

# scale the data so that all values are between 0.0 and 1.0
X = MinMaxScaler().fit_transform(X)

# split two data points from the data as test data and
# use the remaining n-2 points as the training data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=2)
# print(X_train, X_test, y_train, y_test)
# place-holder for the predicted classes
y_predict = np.empty(len(y_test), dtype=np.int64)
# print(y_predict)
# produce line segments that connect the test data points
# to the nearest neighbors for drawing the chart
# lines = []


# distance function
def dist(a, b):
    sum = 0
    for ai, bi in zip(a, b):
        sum = sum + (ai - bi)**2
    return np.sqrt(sum)


# def main(X_train, X_test, y_train, y_test):

    global y_predict
    global lines
    
    # process each of the test data points
for i, test_item in enumerate(X_test):
        # calculate the distances to all training points
    distances = [dist(train_item, test_item) for train_item in X_train]
    print("distance:(14x2)",distances)
#         # find the index of the nearest neighbor
    nearest = np.argmin(distances)
    print("two nearest indext:",nearest)
#         # create a line connecting the points for the chart
    lines.append(np.stack((test_item, X_train[nearest])))
    print("line:",lines)
#         # add your code here:
    y_predict[i] = distances[nearest]
    print(y_predict)
    #this just classifies everything as 0 

#     print(y_predict)


# main(X_train, X_test, y_train, y_test)


distance:(14x2) [0.9189297873955793, 0.7038105085202159, 0.7362270473393815, 0.6416969851116551, 0.22784894381821477, 0.1563207367984219, 0.08450023025374083, 0.6320719369729264, 0.381815714692994, 0.6864538217699051, 0.5794004540122246, 0.6020309000127991, 0.5464160391582199, 0.09567295306912872]
two nearest indext: 6
line: [array([[0.8, 0.4],
       [0.7, 0.6]]), array([[0. , 1. ],
       [0.2, 0.7]]), array([[1. , 0.1],
       [0.8, 0.3]]), array([[0.6, 0.9],
       [0.5, 0.9]])]
[ 0 16]
distance:(14x2) [0.864275502428286, 1.0053240810304482, 0.711054858986254, 0.9481429972969802, 0.5913425877001453, 0.8097716416100927, 0.6879933636116209, 0.8001169811069739, 0.5026671080133638, 0.6029503226740084, 0.8700289064577619, 0.4844943810245051, 0.2735770176261715, 0.8019249543710104]
two nearest indext: 12
line: [array([[0.8, 0.4],
       [0.7, 0.6]]), array([[0. , 1. ],
       [0.2, 0.7]]), array([[1. , 0.1],
       [0.8, 0.3]]), array([[0.6, 0.9],
       [0.5, 0.9]]), array([[0. , 0.4],


In [57]:
import numpy as np
from sklearn.datasets import make_blobs
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


# create random data with two classes
X, y = make_blobs(n_samples=16, n_features=2, centers=2, center_box=(-2, 2))

# scale the data so that all values are between 0.0 and 1.0
X = MinMaxScaler().fit_transform(X)

# split two data points from the data as test data and
# use the remaining n-2 points as the training data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=2)
print("1:",X_train)
print("2:",X_test) 
print("3:",y_train) 
print("4:",y_test)
# place-holder for the predicted classes
y_predict = np.empty(len(y_test), dtype=np.int64)
print(y_predict)

1: [[0.  0. ]
 [0.9 1. ]
 [0.2 0.2]
 [1.  0.8]
 [0.7 0.4]
 [0.6 0.5]
 [0.  0.1]
 [0.2 0.3]
 [0.7 0.2]
 [0.4 0.7]
 [1.  0.7]
 [0.5 0.7]
 [0.4 0.7]
 [0.  0.5]]
2: [[0.5 0.4]
 [0.3 0.1]]
3: [1 0 1 0 0 0 1 1 1 0 0 0 1 1]
4: [0 1]
[0 1]


In [4]:
import numpy as np
data = [[1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1],
        [1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 0, 1, 3, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1]]

def distance(row1, row2):
    total = 0
    for i in range(len(row1)):
        total = total + abs(row1[i] - row2[i])

    # fix this function so that it returns 
    # the sum of differences between the occurrences
    # of each word in row1 and row2.
    # you can assume that row1 and row2 are lists with equal length, containing numeric values.
    return total

row1 = data[1]
row2 = data[2]
print(row1)
print(row2)
print(distance(row1,row2))

[1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1]
5


In [6]:
def all_pairs(data):
    # this calls the distance function for all the two-row combinations in the data
    # you do not need to change this
    dist = np.array([[distance(sent1, sent2) for sent1 in data] for sent2 in data])
    for i in range(N)
    
    nearest_index = np.unravel_index(np.argmin(dist), dist.shape)
    print(dist)
    print(nearest_index)

all_pairs(data)

[[ 0  5  6  5 12]
 [ 5  0  5  4  9]
 [ 6  5  0  3 12]
 [ 5  4  3  0 11]
 [12  9 12 11  0]]
(0, 0)


In [7]:
import math
print(math.log(1.33) )

0.28517894223366247


In [13]:
# DATA BLOCK

text = '''he really really loves coffee
my sister dislikes coffee
my sister loves tea'''

import math

def main(text):
    # split the text first into lines and then into lists of words
    docs = [line.split() for line in text.splitlines()]

    N = len(docs)

    # create the vocabulary: the list of words that appear at least once
    vocabulary = list(set(text.split()))

    df = {}
    tf = {}
    for word in vocabulary:
        # tf: number of occurrences of word w in document divided by document length
        # note: tf[word] will be a list containing the tf of each word for each document
        # for example tf['he'][0] contains the term frequence of the word 'he' in the first
        # document
        tf[word] = [doc.count(word)/len(doc) for doc in docs]
        print(tf[word])
        # df: number of documents containing word w
        df[word] = sum([word in doc for doc in docs])/N
        print(df[word])
    # loop through documents to calculate the tf-idf values
    for doc_index, doc in enumerate(docs):
        tfidf = []
        for word in vocabulary:
            # ADD THE CORRECT FORMULA HERE. Remember to use the base 10 logarithm: math.log(x, 10)
            tfidf.append(tf[word][0] * math.log(df[word])) 

        print(tfidf)

main(text)


[0.2, 0.0, 0.0]
0.3333333333333333
[0.4, 0.0, 0.0]
0.3333333333333333
[0.0, 0.25, 0.25]
0.6666666666666666
[0.0, 0.25, 0.25]
0.6666666666666666
[0.2, 0.0, 0.25]
0.6666666666666666
[0.0, 0.25, 0.0]
0.3333333333333333
[0.0, 0.0, 0.25]
0.3333333333333333
[0.2, 0.25, 0.0]
0.6666666666666666
[-0.21972245773362198, -0.43944491546724396, -0.0, -0.0, -0.0810930216216329, -0.0, -0.0, -0.0810930216216329]
[-0.21972245773362198, -0.43944491546724396, -0.0, -0.0, -0.0810930216216329, -0.0, -0.0, -0.0810930216216329]
[-0.21972245773362198, -0.43944491546724396, -0.0, -0.0, -0.0810930216216329, -0.0, -0.0, -0.0810930216216329]


In [21]:
import numpy as np
import math

text = '''Humpty Dumpty sat on a wall
Humpty Dumpty had a great fall
all the king's horses and all the king's men
couldn't put Humpty together again'''

def find_tfidf(text):
    # tasks your code should perform:
    docs = [line.lower().split() for line in text.split('\n')]
    # 1. split the text into words, and get a list of unique words that appear in it
    vocabulary = list(set(text.split()))
    N = len(docs)
    # a short one-liner to separate the text into sentences (with words lower-cased to make words equal 
    # despite casing) can be done with 
    # docs = [line.lower().split() for line in text.split('\n')
    # 2. go over each unique word and calculate its term frequency, and its document frequency
    tf = {}
    df = {}
    for word in vocabulary:
        tf[word] = [doc.count(word)/len(doc) for doc in docs]
        df[word] = sum([word in doc for doc in docs])/N

    # 3. after you have your term frequencies and document frequencies, go over each line in the text and 
    # calculate its TF-IDF representation, which will be a vector
    tfidf_data = []
    for doc_index, doc in enumerate(docs):
        tfidf = []
        for word in vocabulary:
            if df[word] == 0:
                df[word] = 1
            tfidf.append(tf[word][doc_index] * math.log(1/df[word],10))
        tfidf_data.append(tfidf)
        print(tfidf_data)
        return tfidf_data
    # 4. after you have calculated the TF-IDF representations for each line in the text, you need to
    # calculate the distances between each line to find which are the closest.
def distance(row1,row2):
    sum = 0
    for m,n in zip(row1,row2):
        sum = sum + (m-n)**2
    return np.sqrt(sum)

def find_nearest_pair(data):
    N = len(data)
    dist = np.empty((N,N),dtype = float)
    print(dist)
    for i in range(N):
        for j in range(N):
            if i == j:
                dist[i][j] = 1000000
            else:
                dist[i][j] = distance(data[i],data[j])
    print(dist)
    print(np.unravel_index(np.argmin(dist),(N,N)))

find_nearest_pair(find_tfidf(text))


[[0.10034333188799371, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.10034333188799371, 0.0, 0.0, 0.0, 0.05017166594399686, 0.10034333188799371, 0.0, 0.0]]
[[1000000.]]
[[1000000.]]
(0, 0)


In [4]:
import math, random        	# just for generating random mountains                                 	 
import numpy as np

n = 10000 # size of the problem: number of possible solutions x = 0, ..., n-1

def mountains(n):
  h = [0]*n
  for i in range(50):
    c = random.randint(20, n-20)
    w = random.randint(3, int(math.sqrt(n/5)))**2
    s = random.random()
    h[max(0, c-w):min(n, c+w)] = [h[i] + s*(w-abs(c-i)) for i in range(max(0, c-w), min(n, c+w))]

    # scale the height so that the lowest point is 0.0 and the highest peak is 1.0
  low = min(h)
  high = max(h)
  h = [y - low for y in h]
  h = [y / (high-low) for y in h]
  return h

h = mountains(n)
